Transform get_pull to return full list of open PRs matching commit
EnricoMi/publish-unit-test-result-action pull request #244
Opened 2022-04-03 08:45 UTC by lachaib

resolves #242

2022-04-03 15:02 UTC, EnricoMi requested changes
Thanks for the PR, this really looks like a great "first good issue". Only minor comments.

2022-04-03 15:04 UTC, EnricoMi commented on python/publish/publisher.py
> +            if pulls:
Right, we need this `if` because we still have the `else` here. Maybe we can remove that since `get_pulls` provides us info-level logging.

2022-04-03 16:03 UTC, lachaib commented on python/test/test_publisher.py
> +        gha = self.do_test_get_pulls(settings, search_issues, [pr1,pr2])
Alright, though I'd suggest you make a full pass of `black` formatting to avoid any future hassle on formatting in code reviews 😃

2022-04-03 16:13 UTC, lachaib commented on python/publish/publisher.py
>                               f'commit {commit} as current head or merge commit but none is open')
I kept as much as possible close to original logging to not surprise other users of the action, but I'm ok with you to remove the extra logging

2022-04-03 16:14 UTC, lachaib commented on python/publish/publisher.py
> +            if pulls:
For the time being I will let the `if` to match the `else`, up to you to remove the logging and get rid of the `if`

2022-04-03 19:30 UTC, EnricoMi commented
I have simplified the "hiding comments" logging message and rework the logging in general, plus adjusted the tests.

2022-04-03 19:42 UTC, EnricoMi commented
Looks like this works pretty well: https://github.com/EnricoMi/publish-unit-test-result-action/runs/5807698802?check_suite_focus=true#step:7:11

2022-04-03 19:43 UTC, EnricoMi approved these changes

2022-04-03 19:48 UTC, lachaib commented
Looks like everything is fine, I have no write access so I assume it's up to you to merge the PR, can you please notify me when the change gets released?
Thanks a lot for your precious time :)

2022-04-03 19:56 UTC, merged

2022-04-03 19:56 UTC, EnricoMi commented
Thanks for the contribution!

2022-04-04 11:14 UTC, lachaib commented
Hi @EnricoMi , do you need to create a new release for this change to take effect? This morning the changes didn't take effect on our CI jobs.

2022-04-04 20:44 UTC, EnricoMi commented
I'll release this in a few days.

2022-04-11 08:56 UTC, EnricoMi commented
This has been released.